package day_47_exceptions_continue;

public class CustomException1 {
    public static void main(String[] args) {

       // System.out.println(5 / 0);
       throw new ArithmeticException("whatever we want to say here");

        //ArithmeticException a = new ArithmeticException("some message here");
        //throw a;

//        try {
//            System.out.println(10 / 0);
//        }
//        catch (Exception e){
//            // throwing Run time Exception manually
//          throw new ArithmeticException("Exception2 class line 17");
//        }

        //int num = 23;
        //if (num % 2 !=0){

           // throw new RuntimeException("Just throwing manual run time exception");

    //    }

    }
}
